---
# Copyright 2016, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Ensure host can talk to HTTPS apt repos
  apt:
    pkg: "apt-transport-https"
    state: "{{ galera_client_package_state }}"
    update_cache: yes
    cache_valid_time: "{{ cache_timeout }}"
  register: apt_transport_https_check
  until: apt_transport_https_check is success
  retries: 5
  delay: 2
  tags:
    - galera-client-apt-packages

- name: If a keyfile is provided, copy the gpg keyfile to the key location
  copy:
    src: "gpg/{{ item.id }}"
    dest: "{{ item.file }}"
    mode: '0644'
  with_items: "{{ galera_client_gpg_keys | selectattr('file','defined') | list }}"
  tags:
    - galera-client-apt-keys

- name: Install gpg keys
  apt_key: "{{ key }}"
  with_items: "{{ galera_client_gpg_keys }}"
  loop_control:
    loop_var: key
  register: _add_apt_keys
  until: _add_apt_keys is success
  retries: 5
  delay: 2
  tags:
    - galera-client-apt-keys

- name: Ensure the sources.list.d folder exists
  file:
    path: "/etc/apt/sources.list.d/"
    state: directory
  tags:
    - galera-client-repos

# TODO: Remove the following two tasks in Pike
# They're only required during upgrades transitioning to a
# statically named apt sources file.
- name: Find old sources
  find:
    path: "/etc/apt/sources.list.d/"
    patterns: "^(?!{{ mariadb_repo_filename }})(.+)|(.+)(?<!{{ mariadb_repo_filename }})\\.list$"
    contains: "^.*maria.*$"
    use_regex: true
  register: old_sources
  tags:
    - galera-client-repos

- name: Remove old sources
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ old_sources.files | default([]) }}"
  tags:
    - galera-client-repos

- name: Remove old galera repo
  lineinfile:
    dest: /etc/apt/sources.list.d/{{ mariadb_repo_filename }}.list
    regexp: "^((?!{{ galera_client_repo }}).*)$"
    state: absent
  tags:
    - galera-client-repos

- name: Add galera repo
  apt_repository:
    repo: "{{ galera_client_repo }}"
    filename: "{{ mariadb_repo_filename }}"
    state: present
    update_cache: no
  register: add_repo
  tags:
    - galera-client-repos

- name: Update Apt cache
  apt:
    update_cache: yes
  when: add_repo is changed
  register: update_apt_cache
  until: update_apt_cache is success
  retries: 5
  delay: 2
  tags:
    - galera-client-repos
